FROM nvidia/cuda:12.8.1-runtime-ubuntu24.04
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --break-system-packages --no-cache-dir -r requirements.txt
COPY requirements-gpu.txt .
RUN pip install --break-system-packages --no-cache-dir -r requirements-gpu.txt
COPY app ./app
COPY training ./training
COPY controllers ./controllers
EXPOSE 8000
CMD ["python3", "-m", "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]
